services:
  unglibrary:
    image: unglibrary:latest
    container_name: unglibrary
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Etc/UTC
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/booklore
      - DATABASE_USERNAME=booklore
      - DATABASE_PASSWORD=booklore
      - ALLOWED_ORIGINS=*
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9999:6060"
    volumes:
      - ./data:/app/data
      - ./books:/books
      - ./bookdrop:/bookdrop
    healthcheck:
      test: wget -q -O - http://localhost:6060/api/v1/healthcheck
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    restart: unless-stopped

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=booklore
      - MYSQL_DATABASE=booklore
      - MYSQL_USER=booklore
      - MYSQL_PASSWORD=booklore
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-pbooklore"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mariadb_data:
